server:
    port: 8090
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: yxg
      password: yxg
      database: microservice
      authenticationDatabase: microservice
  datasource:
    url: jdbc:mysql://localhost:3306/mmj_account?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: aaaa1111

async-config:
  corePoolSize: 5
  maxPoolSize: 10
  queueCapacity: 25